### ISSUE TITLE
Blocked in procesarMatrices

### ISSUE THREAD

**Issue by BenjaminLiu1003** [joanmtg/digits-recognition#1]
I tried to run your project, but it got stuck in Recognition::procesarMatrices.

I would really appreciate it if you could tell me what step i missed to run the project.

**Comment by joanmtg** [comment]
Hi @BenjaminLiu1003, please pull the project again. I guess the problem was related to the fact that this folder was missing.

**Comment by BenjaminLiu1003** [comment]
Thanks so much. But that's not the issue.
It actually got stuck in the recognition.cpp ( line 319 ).
`JAMA::SVD<double> decomposicion = JAMA::SVD<double>(A);`
